apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: msa-api
  name: msa-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: msa-api
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: docker
        image: shelleg/msa-api:config
        name: msa-api
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
