apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: msa-poller
  name: msa-poller
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: msa-poller
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://msa-api:8080
        image: shelleg/msa-poller:latest
        name: msa-poller
        resources: {}
      restartPolicy: Always
status: {}
